### PR TITLE
PPC: Information improvements

### PR DESCRIPTION
**Pull request by bp0**
Based on the recent ARM work.

* Shows multiple processors, like x86 and ARM
* topology: physical package and core ids
* cpufreq: min/max/cur frequency and driver info

Tested against /proc/cpuinfos from a PowerMac G5 and the
Talos POWER8 workstation. Not tested on actual hardware.

### CODE REVIEW

**Comment by mckaygerhard** [comment]
hi @bp0, either me, not have a ppc arch so i cannot test those improvement that for sure are great..  
but seems i can test in a mac/apple from 2013 with live disk of debian, that can work?

**Comment by lpereira** [comment]
Thanks -- I'll test this on my Powerbook G4 later tonight.

**Comment by bp0** [comment]
@mckaygerhard, if it doesn't have a ppc processor, then no.

@lpereira, right on.

**Comment by lpereira** [comment]
It's much better on ppc, thanks!

**Pull request merged**
