### PR TITLE
korean translate update

### PR DESCRIPTION
**Pull request by yunlisa96**
I requested a pull request again because there was a part to be corrected in the previous pull request. Please check

### CODE REVIEW

**Comment by lpereira** [comment]
Thanks! I'll merge this as soon as I can. (I'm taking a break from this project so it might take a while.)

**Comment by hamishmb** [comment]
@lpereira, I'm interested in this project - if you'd like another dev to review MRs and make minor changes, I'd be happy to join you. I don't have time to do all of it myself, but I could certainly help if you'd like a hand.

**Comment by lpereira** [comment]
Merged!  Gansahabnida!  (I squashed everything in a single commit to make things easier, so it will still show up here as unmerged.)


@hamishmb: That would be helpful, but please understand I can't just give repository push rights without knowing how you'd be as a maintainer.  You're welcome to contribute and as soon as you've been around for a while, that's definitely something that can be done.

**Comment by hamishmb** [comment]
@lpereira Of course, I wasn't assuming that you'd do that - just thinking ahead :)

**Comment by hamishmb** [comment]
@lpereira, would it be useful if I review and test code in some of the existing merge requests when I get some time?

**Comment by lpereira** [comment]
Feel free to!

**Comment by hamishmb** [comment]
Okay, shall do :)

**Comment by lpereira** [comment]
Closing as this has been merged already.

**Pull request closed without merging**
