### PR TITLE
Raise GTK2 requirement from 2.10 to 2.18

### PR DESCRIPTION
**Pull request by bp0**
As links in labels are now being used, 2.18 is required.

See: https://github.com/lpereira/hardinfo/issues/379#issuecomment-507857291

### CODE REVIEW

**Comment by mckaygerhard** [comment]
hi! i see the comment and well, today.. a recent version of hardinfo only compiles in recent version of gcc and linux.. that again does are not well performed in those arm based old devices.. 

i was the objection in that past comment.. but i cannot able to compile hardinfo in those rasberry devices.. and i have many.. i Debian 10, fedora 7 are too heavy distributions for that falvors devices.. so compile recent hardinfo version are now nonsense.. 

we used hwinfo instead.. **the cause: issue  related to pull #160 since commit 3f18100  so if hardinfo does not compiled in glibc << 2.11 there's no sense for those older systems still running kernel 2.6 and 3.0, due unsuported hardware in recent kernels like good pool network cameras and security related, also many spensive multimedia devices wtill good working but very older**

**Comment by bp0** [comment]
After this change, requires: cmake 2.6+, gcc 4.6+, gtk 2.18+, glib 2.10+. So any of Debian 5.0+, Ubuntu 8.04+, Slackware 13.0+, or about 10 years... if you can get the source downloaded on such old systems, as git clone will not work, neither will wget be able to connect with SSL to github.

As for hardware I've tested on Raspberry PI 1B, 1x ARM11 900Mhz, Raspbian 8 Jesse, and on an old 1.4Ghz Pentium 4, and all worked.

I really like to support old Linux and old hardware as much as possible, but also like new features. It's unfortunate that hardinfo doesn't have a stronger separation between the core and the GUI bits so that they could have different requirements.

**Comment by mckaygerhard** [comment]
> unfortunate that hardinfo doesn't have a stronger separation between the core and the GUI bits so that they could have different requirements.

well consider that hardinfo are more than 10+ years old .... in those days the client-server behaviour was (and still are) not the most faster..  a socket/client separation are themost good behaviour in unix-linux like environments

> After this change, requires: cmake 2.6+, gcc 4.6+, gtk 2.18+, glib 2.10+. So any of Debian 5.0+, Ubuntu 8.04+, Slackware 13.0+, or about 10 years... 

that raised to any Debian 7.0+, Winbuntu 14+, Slack 13+

> if you can get the source downloaded on such old systems, as git clone will not work, neither will wget be able to connect with SSL to github.

my wget backport works.. also my git under Debian ETCH !!!

**Comment by bp0** [comment]
I tried hardinfo in void linux, which has no systemd, and no udev for udisks2, and it worked. The fallback methods for storage include lsscsi, which does actually report nvme devices, and /proc/scsi/scsi which does not report nvme, but it only available on older kernels which probably don't support nvme anyway? Do you have a Debian etch system with an nvme device?

I tried to test etch, but it is not supported by debian anymore. The archive is not available, and the DVDs can't even be downloaded anymore. I'm curious what exact board you might have that <s>is</s> <b>WAS</b> supported by Debian etch, but not by void linux currently?

**Comment by lpereira** [comment]
Maybe for the links we can `#ifdef` and not generate one, so that we can release a last version supporting older GTK+ versions?  Or is that not the case anymore, and 2.18 is indeed the minimum supported version?

**Comment by bp0** [comment]
Ok lets just put in #ifdefs, but honestly does anyone have an idea what old version of GTK is really supported? As I mentioned, GTK 2.18 was added in Debian 5 Lenny (February 2009). I tried to build hardinfo in earlier debian, but failed because git and openssl were too old to even fetch the source, and I didn't care to continue.

**Comment by bp0** [comment]
Close in favor of #436.

**Pull request closed without merging**
