### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by bp0** [comment]
lgtm, and by me, i mean me using google translate.

**Comment by mckaygerhard** [comment]
if are using google translator for made russian translation that explain some "rare" strings.. i not taking but i read little and some string need revision..

PLEASE DO NOT USE GOOGLE TRANSLATOR FOR RUSSIAN CONTEXT TEXTS, its the wors translator for russian

**Comment by bp0** [comment]
I didn't translate the English strings to Russian via Google Translate, I translated TC's Russian strings to English to check them, and they appear to be OK.

**Comment by mckaygerhard** [comment]
that's better! but dont trust on that either.. i use the yandex translation due has more words but th translations are still not enought..

**Comment by lpereira** [comment]
Merged, spasibo!

**Pull request merged**
