### PR TITLE
Added GTK3 support (unfinished, need help)

### PR DESCRIPTION
**Pull request by TotalCaesar659**
OK, here is my sketches of adding GTK3 support to HardInfo. After compiling with gtk3, there are error messages something like this:

>/home/maxpayne/hardinfo/shell/shell.c:841:51: error: ‘GtkScrolledWindow {aka struct _GtkScrolledWindow}’ has no member named ‘vscrollbar’
          (GTK_SCROLLED_WINDOW(shell->tree->scroll)-> \
                                                   ^
/usr/include/glib-2.0/gobject/gtype.h:2207:57: note: in definition of macro ‘_G_TYPE_CIC’
     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                         ^
/usr/include/gtk-3.0/gtk/gtkrange.h:40:36: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
 #define GTK_RANGE(obj)            (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_RANGE, GtkRange))
                                    ^
/home/maxpayne/hardinfo/shell/shell.c:840:26: note: in expansion of macro ‘GTK_RANGE’
      gtk_range_get_value(GTK_RANGE \
                          ^
/home/maxpayne/hardinfo/shell/shell.c:856:23: note: in expansion of macro ‘RANGE_GET_VALUE’
     pos_info_scroll = RANGE_GET_VALUE(info, vscrollbar);
                       ^

I don't know how to solve them, so I hope that it may be some starting point for further implementing of GTK3.

### CODE REVIEW

**Comment by mckaygerhard** [comment]
there's still some prjects like lxde that nver will swicth to gtk3, (seems quite obviously slower) so why populate the code of simplicity to a large conditionals.. hardinfo its for ligths-single desktops focused.. if a more complex or moder its the wnated.. people can use some of nmayor dessktop providers.. 

and today since the commit 907a624 i cannot compile.. with light true desktops, (due recents version of soup require too recent version of glib, that also required too recent version of glibc) there's no sence to use too "up to date fashion" its are working well, and if not compile with recent , recent environment can use modern software.. of modern choices..

**Comment by lpereira** [comment]
Thanks for this, @TotalCaesar659! I'll take a look during the weekend and see if I can fix those warnings/errors.

As far as the building problem on old libsoup versions: you can build without libsoup. The server isn't working any longer (lost the source and the database, and had no backup), so won't impact anything.  And, as far as supporting GTK+2: it's complicated to support two versions of GTK+, and there's not enough manpower to do so.  HardInfo supported 1.2 and 2.0 series during 0.3.x -- and it was quite a hassle.  And GTK+2 is not well supported anymore, so it seems prudent to move on.

**Comment by mckaygerhard** [comment]
i was working in a patch for libsoup but as u said, its unsense... so waste the work..

about GTK2, its not as u said.. LXDE a very used and often famous desktop will never migrate to GTK3.. due GTK3 have some problems on performance.. so a tarject point on "lightweith" way maybe must be considered

**Comment by TotalCaesar659** [comment]
> there's still some prjects like lxde that nver will swicth to gtk3

Well, if you say so, that you've got official statement from LXDE developers. Share it with us. Statements without prooves are nothing.
> people can use some of nmayor dessktop providers..

They also can build HardInfo with GTK3 and use it, without getting somebody's opinion.
> and today since the commit 907a624 i cannot compile.. with light true desktops

Shouldn't it be good to create separate ticket for it? Or you just try to direct the discussion in another way?
> there's no sence to use too "up to date fashion" its are working well

And it works well now, with implementing of GTK3. It builds correctly with GTK2, as its old versions. If you don't want to use GTK3 - OK, nobody forces you. But speaking for the others - it's not best way for discussion.
> if not compile with recent , recent environment can use modern software.. of modern choices..

Again, this is HardInfo repo, and everyone can try to make it better.
Besides, I don't like GTK3 development very much for its constant problem with compatibility, but I don't like calcification and misoneism more.
>about GTK2, its not as u said.. LXDE a very used and often famous desktop will never migrate to GTK3.. due GTK3 have some problems on performance.. so a tarject point on "lightweith" way maybe must be considered

As I already said, nobody removes GTK2 support. You can use it as earlier. GTK3 doesn't have an influence for it.
>Thanks for this, @TotalCaesar659! I'll take a look during the weekend and see if I can fix those warnings/errors.

Thanks for the answer! Of course, I tried to do what I could - removing many compile warnings etc., but I can't go further cause of my lack of programming skill. So I've decided to release it in public. I hope somebody will make it better, it would be good for version 6 changelog.

**Comment by mckaygerhard** [comment]
the lxde wiki said all about: and pcman also said.. that why they made the lxqt project due gtk3 problems.. 

well its enought to know that gtk2 will never be removed

i'll try to provide all the collaboration to made available to gtk2 older users with patcheds and pull requets

**Comment by lpereira** [comment]
I just took a look.  Indeed it needs some work to get this to a point where one can pick which version of GTK+ to build HardInfo with.  But it's a good start, indeed!  I just cannot help finishing your work at the moment, as I'm very busy with other projects.

**Comment by TotalCaesar659** [comment]
OK, I hope you'll solve it. Don't forget about it at all ))

**Comment by bp0** [comment]
Hi, I fixed up all the direct refs as described https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html#id-1.6.3.3.5 and now I can get it to compile (although with many deprecation warnings).
However, it fails while linking.
I tried this in CMakeLists.txt:
```
pkg_check_modules(GTK REQUIRED gtk+-3.0>=3.10 cairo>=1.0 glib-2.0>=2.10 gthread-2.0>=2.10 gmodule-export-2.0>=2.10)
```
Error is now:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libgtk-3.so: undefined reference to symbol 'cairo_rectangle'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcairo.so: error adding symbols: DSO missing from command line
```
Any ideas?

**Comment by lpereira** [comment]
That's a strange error to happen, specially if CMake is being used with `target_link_libraries` (which HardInfo uses).  If you build with `make VERBOSE=1`, it should print the command line arguments passed to the compilers/linkers, and that might help figure out what's happening here.

**Comment by bp0** [comment]
```
/usr/bin/cc     CMakeFiles/hardinfo.dir/hardinfo/binreloc.c.o CMakeFiles/hardinfo.dir/hardinfo/expr.c.o CMakeFiles/hardinfo.dir/hardinfo/hardinfo.c.o CMakeFiles/hardinfo.dir/hardinfo/socket.c.o CMakeFiles/hardinfo.dir/hardinfo/util.c.o CMakeFiles/hardinfo.dir/hardinfo/vendor.c.o  -o hardinfo -rdynamic -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lcairo -lpng16 -lgthread-2.0 -lgmodule-2.0 -lglib-2.0 libhardinfo-shell.a -lm -lz 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libgtk-3.so: undefined reference to symbol 'cairo_rectangle'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcairo.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/hardinfo.dir/build.make:226: recipe for target 'hardinfo' failed
```

`-lcairo` is in there.

**Comment by lpereira** [comment]
It's maybe `libhardinfo-shell.a` that's in the wrong order. You can try fixing this by removing its library declaration from `CMakeLists.txt`, and adding its sources to the hardinfo target directly.  (Basically move all `.c`from `add_library(hardinfo-shell ...)` to `add_executable(hardinfo ...), and remove `hardinfo-shell` from `target_link_libraries()`.

**Comment by bp0** [comment]
Well that changes something.
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/hardinfo.dir/link.txt --verbose=1
/usr/bin/cc     CMakeFiles/hardinfo.dir/hardinfo/binreloc.c.o CMakeFiles/hardinfo.dir/hardinfo/expr.c.o CMakeFiles/hardinfo.dir/hardinfo/hardinfo.c.o CMakeFiles/hardinfo.dir/hardinfo/socket.c.o CMakeFiles/hardinfo.dir/hardinfo/util.c.o CMakeFiles/hardinfo.dir/hardinfo/vendor.c.o CMakeFiles/hardinfo.dir/shell/callbacks.c.o CMakeFiles/hardinfo.dir/shell/iconcache.c.o CMakeFiles/hardinfo.dir/shell/loadgraph.c.o CMakeFiles/hardinfo.dir/shell/menu.c.o CMakeFiles/hardinfo.dir/shell/report.c.o CMakeFiles/hardinfo.dir/shell/shell.c.o CMakeFiles/hardinfo.dir/shell/stock.c.o CMakeFiles/hardinfo.dir/shell/syncmanager.c.o  -o hardinfo -rdynamic -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lcairo -lpng16 -lgthread-2.0 -lgmodule-2.0 -lglib-2.0 -lm -lz 
CMakeFiles/hardinfo.dir/shell/callbacks.c.o: In function `cb_about_module':
callbacks.c:(.text+0x582): undefined reference to `gtk_about_dialog_set_name'
CMakeFiles/hardinfo.dir/shell/callbacks.c.o: In function `cb_about':
callbacks.c:(.text+0x8ca): undefined reference to `gtk_about_dialog_set_name'
CMakeFiles/hardinfo.dir/shell/loadgraph.c.o: In function `load_graph_set_color':
loadgraph.c:(.text+0x2f1): undefined reference to `gdk_rgb_gc_set_foreground'
loadgraph.c:(.text+0x315): undefined reference to `gdk_rgb_gc_set_foreground'
loadgraph.c:(.text+0x339): undefined reference to `gdk_rgb_gc_set_foreground'
CMakeFiles/hardinfo.dir/shell/loadgraph.c.o: In function `load_graph_destroy':
loadgraph.c:(.text+0x37c): undefined reference to `gdk_pixmap_unref'
CMakeFiles/hardinfo.dir/shell/loadgraph.c.o: In function `load_graph_configure_expose':
loadgraph.c:(.text+0x488): undefined reference to `GDK_DRAWABLE'
loadgraph.c:(.text+0x494): undefined reference to `gdk_gc_new'
loadgraph.c:(.text+0x4b5): undefined reference to `GDK_DRAWABLE'
loadgraph.c:(.text+0x4c1): undefined reference to `gdk_gc_new'
loadgraph.c:(.text+0x4e2): undefined reference to `GDK_DRAWABLE'
loadgraph.c:(.text+0x4ee): undefined reference to `gdk_gc_new'
CMakeFiles/hardinfo.dir/shell/loadgraph.c.o: In function `_draw_label_and_line':
loadgraph.c:(.text+0x640): undefined reference to `GDK_DRAWABLE'
loadgraph.c:(.text+0x662): undefined reference to `gdk_draw_line'
CMakeFiles/hardinfo.dir/shell/loadgraph.c.o: In function `_draw':
loadgraph.c:(.text+0x8ba): undefined reference to `gdk_draw_polygon'
loadgraph.c:(.text+0x8ec): undefined reference to `gdk_draw_polygon'
loadgraph.c:(.text+0x96a): undefined reference to `gdk_draw_line'
CMakeFiles/hardinfo.dir/shell/shell.c.o: In function `set_view_type':
shell.c:(.text+0x29da): undefined reference to `gtk_notebook_set_page'
shell.c:(.text+0x2a6d): undefined reference to `gtk_notebook_set_page'
shell.c:(.text+0x2b4a): undefined reference to `gtk_notebook_set_page'
shell.c:(.text+0x2bfe): undefined reference to `gtk_notebook_set_page'
collect2: error: ld returned 1 exit status
```
Now I wonder why `gtk_about_dialog_set_name` wasn't caught during compilation of callbacks.c?

**Comment by bp0** [comment]
It did finally build, but crashes immediately. Progress, I guess.

**Comment by lpereira** [comment]
I'm closing this in favor of #114 that continues this work. Thanks, @TotalCaesar659 and @bp0!

**Pull request closed without merging**
