### PR TITLE
[WIP; Don't Merge] Unify DMI and SPD memory information into one "Memory Devices"

### PR DESCRIPTION
**Pull request by bp0**

### CODE REVIEW

**Comment by bp0** [comment]
First with no information, second with only SPD, third with both DMI and SPD. Should work with DDR2,3,4. spd-decode.c is a bit of a mess to try and reform.
Screenshot from 2019-06-27 02-05-32
Screenshot from 2019-06-27 02-06-46
Screenshot from 2019-06-25 18-42-35

**Comment by lpereira** [comment]
Looking good!

**Comment by bp0** [comment]
It seems in pretty good shape, but I can't test very much. I have several DDR3 machines, and one DDR4 machine, but the ee1004 driver doesn't work on the DDR4 machine for some reason.
@lpereira or @ocerman , if you have some DDR4 machines could you test it out and maybe even post some screengrabs or the "Memory Devices" section of `sudo hardinfo -r -f text -s -w`?

**Comment by lpereira** [comment]
[Some screengrabs from my DDR4 machine are here](https://imgur.com/a/uc62SYo).  Unfortunately the ee1004 module doesn't give out any information here either.

**Comment by bp0** [comment]
Thanks. Do you get any extra information with the regular eeprom module?

**Comment by bp0** [comment]
@lpereira , it seems that there is no auto-detect of devices yet. Also, eeprom and ee1004 will compete so they must not be loaded together.
The process to configure the ee1004 devices is described at https://www.spinics.net/lists/linux-i2c/msg32331.html
After following this guide, I was able to see the DDR4 SPD information, but this is not a great experience yet.

**Comment by bp0** [comment]
Of course, @ocerman  said all of that in his original PR #334. Sorry for my ignorance.

**Pull request closed without merging**
