### PR TITLE
Translation support fixes, device tree support, x86 bug detection fix, others

### PR DESCRIPTION
**Pull request by bp0**
Mostly described in commit messages.

For "Make locale dir match install path", the default install location is /usr/local/  but the hard-coded messages location was "/usr/share/locale". This bug was a bit frustrating to find.

### CODE REVIEW

**Comment by bp0** [comment]
Regarding the conflict in po/ru.po, the file from this branch should just replace the one in master.

**Comment by lpereira** [comment]
Thanks again for the changes! I'll review them as soon as I have some free time.

However, making large pull requests such as these makes it really difficult to review them at once. There's no need to do this for this one, but please consider making smaller, just-one-topic pull requests in the future. I've noticed you often re-fork the repository; that's not really necessary, and if you need some help with Git I can give you a few pointers.

**Comment by bp0** [comment]
@lpereira 
> However, making large pull requests such as these makes it really difficult to review them at once. There's no need to do this for this one, but please consider making smaller, just-one-topic pull requests in the future. I've noticed you often re-fork the repository; that's not really necessary, and if you need some help with Git I can give you a few pointers.

Alright. I try to split them in the future.

**Comment by bp0** [comment]
The Device Tree support is now working well. Here are some screen captures.
dt_root
dt_dsi
dt_cpu
dt_3v3

**Comment by mckaygerhard** [comment]
great! a great improvement, but now has some conflict the russian update, we must coordinate the effors wit large commits.. 

@lpereira please take in consideration that idea for avoid conflicts and better prformant coordination over the overall work:
@bp0, and @TotalCaesar659 **for now, its better separate commits by categorization** as *example: separate functuional code from translation code.. * by this way trivial conflict like the ru.po with the pull #94 will not happened.. that pull of @TotalCaesar659 are good due only takes and coverts over the translation file at one specific point no conflicting over other important files by example for you that touch iportant files over an important featured!

also by separate the pull's by functionality, avoid extra work revision for @lpereira due your large commits (i understand that this featured need all of those changes, but there many commits here ok)

now @TotalCaesar659 please sync and update your pull of the russian translation, that's why i still not take any improvement over the spanish translation until commits get lower activity and coordinate ...

great work @bp0 !

**Comment by mckaygerhard** [comment]
great! a great improvement, but now has some conflict the russian update, we must coordinate the effors wit large commits.. 

@lpereira please take in consideration that idea for avoid conflicts and better prformant coordination over the overall work:
@bp0, and @TotalCaesar659 **for now, its better separate commits by categorization** as **_example: separate functuional code from translation code.._** by this way trivial conflict like the ru.po with the pull #94 will not happened.. that pull of @TotalCaesar659 are good due only takes and coverts over the translation file at one specific point no conflicting over other important files by example for you that touch iportant files over an important featured!

also by separate the pull's by functionality, avoid extra work revision for @lpereira due your large commits (i understand that this featured need all of those changes, but there many commits here ok)

now @bp0 please sync and update your pull of the russian translation, that's why i still not take any improvement over the spanish translation until commits get lower activity and coordinate ...

great work @bp0 !

EDITED: corrected the user citation!

**Comment by lpereira** [comment]
Nice work on the device tree.  I've merged this PR, but due to conflicts in the potfiles, commits affecting them were not picked up during rebase.

**Comment by mckaygerhard** [comment]
@lpereira i have the idea to put that i cited in a CONTRIBUTE new file.. what do you think? with a minimal coding style and some development info about the plugin behaviour

**Comment by bp0** [comment]
@lpereira 
> Nice work on the device tree

Thanks, but I only have Raspberry Pis to test it on. Could you send your PowerMac device tree?
`dtc -I fs /proc/device-tree >pmac.dts`

> due to conflicts in the potfiles, commits affecting them were not picked up during rebase.

PR #96 should reconcile them.

**Comment by lpereira** [comment]
Sure, will send you the Mac Device Tree.

**Comment by mckaygerhard** [comment]
my dtc only has device tree here `sys/firmware/device-tree` and not n proc, i dont know:   
```
/dts-v1/;

/ {
};
```

**Comment by mckaygerhard** [comment]
nop. for now i not have enought info, i'll chek more in my home computer, was revised in a debian 8 minimal install (dtc command i must installed and others supports) already know about the soft link but are not in that place, i'll check then in the home machine and report feeed back after a better restart at home (in my work machines almost any can be restarted due have many many things opened/working jej je)

please review the pull about contribution file, i update respect the previous already commited by bp0

**Comment by bp0** [comment]
@mckaygerhard 
Add your candidate device tree root locations here:
https://github.com/lpereira/hardinfo/pull/97/commits/3063f1343a45331a4aa9042ac1202028e6d8d7ac#diff-7ea8ad6e2122d2d65eb659fe69be041bR199

@lpereira @mckaygerhard 
Any Device Tree machines you want to capture into .dts? Please send them to me or put them in test/data (See #97)

**Comment by mckaygerhard** [comment]
ok, my only arm machine does are too older to property boot device tree activate.. and its using a squeeze debian image with 3.2 linux (debian 6 due are very faster and light, more than recents)

i have a i386 machine in my work with device tree but does not describe nothing.. 

now **i think device tree now its a arm-related specific feature**

please some one can ilustrate me?, due i already know that device tree are since kernel 3.12 available.. and property madure at kernel 4.4 in linux  but all the info and tech i found refered to arm arch!

in my i386 i only have `/sys/firmware/devicetree/` in the arm also same, but the tree are not available more that the node root

**Comment by bp0** [comment]
@mckaygerhard
Device Tree is used in arm, power/ppc, sparc, and riscv, but not in x86.

**Comment by mckaygerhard** [comment]
arrgg that's jappened to not read before! device tree its supported also in x86 but efforts to implementing are very vage,  DT are mandatory now in all arm/on-chip based devices/machines but in some time was not mandatory... i have a very older Rpi (at my work in the depot) that does not have and still use ATAGs 

so ok then please take case when DT are not available i have a very older kernel in that device (that today i used due this commit ja ja but no again.. its tediious get down to the depot)

**Comment by bp0** [comment]
Everything is merged, and the conflicts resolved. Closing.

**Pull request closed without merging**
