### PR TITLE
CONTRIBUTING -> CONTRIBUTING.md; copyedit

### PR DESCRIPTION
**Pull request by mckaygerhard**
a starter contributors file permits more coders to send pulls and can aprove more quickly avoid waste time in reviews

### CODE REVIEW

**Comment by bp0** [comment]
>  identations: Currently the code use as default a TAB for identations
* There are a mix of spaces and tabs for indentation in the code. I use spaces, so when I edit a file, I usually convert the tabs to spaces. 

Also, 
* The document has too much unnecessary exposition. Most will tl;dr. In my opinion, bullets only, until a request for clarification. API documentation should appear elsewhere.
* The English seems poor, but I am not an expert.

**Comment by mckaygerhard** [comment]
pushed some commits as per request.. reduce the file let only necesary info in minimal needs

**Comment by mckaygerhard** [comment]
reduce the file and pass sell check to english, improve redaction! done all!

**Comment by bp0** [comment]
Closing in favor of #467.

**Pull request closed without merging**
