### PR TITLE
po/es.po: Save some old translated strings; clear obsolete strings

### PR DESCRIPTION
**Pull request by bp0**

### CODE REVIEW

**Comment by bp0** [comment]
If other translation updates are ready, pull those first and I'll resolve the conflicts.

**Comment by mckaygerhard** [comment]
hi! @bp0 i finish the es.po translations, but now with this update , i only must run the shell script and all the strings will be updated?

**Comment by bp0** [comment]
@mckaygerhard 
You don't have to. Ideally you should have run it before you started, but it was just run before a recent commit so everything should be fine. You can also run it after you rebase to master and it will update the .po files with any new or changed strings, but no existing translations will be lost. Some may be made obsolete, but they will still be in the file. 

Regarding my update here, after your PR #136 is merged, I will resolve the conflicts and update this pull request. You don't have to do anything.

**Comment by mckaygerhard** [comment]
O.o   
.. errr ok ok .. wow! can also server me a coffe! with cream please!  ;-)

**Comment by bp0** [comment]
Updated and ready to merge.

**Comment by mckaygerhard** [comment]
My coffe! my coffe!

**Comment by bp0** [comment]
Included in #151, closing.

**Pull request closed without merging**
