### PR TITLE
[WIP] storage: updated device label

### LINKED ISSUE #507: NVMe SSD vendor name doubled
double-samsung

### PR DESCRIPTION
**Pull request by ocerman**
FIX #507 

@bp0 can you check whether this works well also for your SSD?

### CODE REVIEW

**Comment by bp0** [comment]
None of my NVMe SSDs have the exact problem of name in model, but I have some thoughts. I think the vendor match from model should happen in udisks2_util.c instead of storage.c. 

The existing code was trying to get vendor out of model to handle the problem of SATA always having ATA for vendor anyway, but for NVME, if we have a match from model we have potentially two vendors, the PCB vendor and the controller vendor. Consider "Force MP500" could match Corsair for me, and still have Phison for the controller vendor, while for your Samsung, you could have the two vendors as well, even though they're the same, as Samsung makes its own controllers. 

There is still a problem of potential double-vendors when composing the list, but that problem already existed, like with your Toshiba drives there.

**Comment by bp0** [comment]
I think my solution to the double vendor problem was just to use the tags for the vendor part, and let it be double, but with the colored tags it didn't really look so bad.

Screenshot_2020-01-01_07-23-34

**Comment by bp0** [comment]
Btw, using a `vendor_list` with `vendor_list_remove_duplicates_deep()` may be useful here. Vendors are keyed on their match strings so one Vendor *v->name="Samsung" may not match another Vendor *v->name="Samsung".

**Comment by bp0** [comment]
Ok, sorry to spam, but I've been looking into it some more and there is already a `vendor_list` in `struct udiskd` that could be used to make a ribbon of tags with `vendor_list_ribbon()`. 

Also, I think maybe we could add a member `pcid *pci_controller` to `struct udiskd` with all the PCI information and then using code from pci.c, we get all controller vendor/subvendor and even the PCI express information along with it.

**Comment by bp0** [comment]
Alright I've added the PCIe info for NVMe devices in #511. Note that it doesn't fix your double Samsung problem.

**Comment by ocerman** [comment]
Yes, color vendor tag + model string seems like best solution. In the end it could look like this (please ignore that "samsung" tag is on toshiba/st drives)

new-storage

I will try to finish it tomorrow as right now it has some issues (because same list is also used in computer->hi_module_get_summary)

**Comment by bp0** [comment]
Yes, I think that is the right way to go. Maybe rebase your changes off of #511 to avoid conflict. If you want I can cherry-pick your commit(s) into that PR to avoid conflicts.

**Comment by ocerman** [comment]
@bp0 I have updated the code. Now it should work all fine, also fallback functions now follow same layout.

To get storage devices displayed correctly on homepage I had to create function `getStorageDevicesSimple`, but if you know better way how to do it feel free to change it. 

@bp0 Can you try to cherrypick it? I will close this PR.

**Comment by bp0** [comment]
Done, this commit is now in #511.

**Pull request closed without merging**
