### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by lpereira** [comment]
Merged, spasibo!

**Comment by bp0** [comment]
@TotalCaesar659 
The translation of Desktop Environment is a duplicate of Home Directory, and having the same label causes hardinfo to display Desktop Environment twice. Could you provide a translation?

https://github.com/lpereira/hardinfo/blob/685d931a6d0e965386e442e6ea25d17bb3322806/po/ru.po#L752

**Comment by lpereira** [comment]
@bp0 Just fixed the translation. I hope it's right. (I can read cyrillic but my Russian vocabulary is limited to complicated words such as "hello" and "thanks".)

**Comment by bp0** [comment]
Wfm, that's more Russian than I know. :smile:

**Comment by mckaygerhard** [comment]
i already know some russian, less limited rather than, dont trust on google's translator, its very bad with russian... i'll chek the duplicate problem after updates of  the #92 pull from @bp0

**Pull request merged**
