### PR TITLE
move devices/memory to computer/memory usage

### PR DESCRIPTION
**Pull request by bp0**
As discussed in https://github.com/lpereira/hardinfo/issues/345.

Everything seems to be working, except there is now a message at startup:
> Module "Computer" depends on module "devices.so"

Didn't it always? I'm not sure what I changed that causes this message. This also blocks benchmarks from working, because the spawned process dies with this message.
Maybe @lpereira could fix that?

### CODE REVIEW

**Comment by lpereira** [comment]
Making various modules was a mistake.  I've considered rewriting HardInfo a million times and getting rid of this mess is one of those things that makes the top 5 reasons to do so.  (The shell communicating with the modules via a .ini-style string is number 1 though.)

I'll take a look, see how hard it is to fix this warning/error.

**Comment by lpereira** [comment]
Ah, the reason is that the `devices.so` module requires the `memlabels` GHashTable, but it's defined in `computer.so`.  Just pushed a commit that debug-prints the value of `g_module_error()` when loading a module.

**Comment by bp0** [comment]
Alright, should be fixed.

**Comment by lpereira** [comment]
Merged, thanks!

**Pull request merged**
